import {
  ServiceCategory,
  Provider,
  Job,
  MessageThread,
  ChatMessage,
  Invoice,
  Receipt,
  Review,
  Quote,
  HomeownerProfile,
  TimeSlot,
  Address,
  PaymentMethod,
} from "./types";

export const SERVICE_CATEGORIES: ServiceCategory[] = [
  { id: "cat-1", name: "Plumbing", icon: "droplet", description: "Pipes, fixtures, water heaters, and drainage" },
  { id: "cat-2", name: "Electrical", icon: "zap", description: "Wiring, outlets, lighting, and panels" },
  { id: "cat-3", name: "HVAC", icon: "wind", description: "Heating, cooling, ventilation systems" },
  { id: "cat-4", name: "Cleaning", icon: "home", description: "Deep cleaning, regular maintenance, move-in/out" },
  { id: "cat-5", name: "Landscaping", icon: "sun", description: "Lawn care, gardening, tree services" },
  { id: "cat-6", name: "Painting", icon: "edit-3", description: "Interior, exterior, staining, wallpaper" },
  { id: "cat-7", name: "Roofing", icon: "umbrella", description: "Repairs, replacements, inspections" },
  { id: "cat-8", name: "Handyman", icon: "tool", description: "General repairs, installations, assembly" },
];

export const PROVIDERS: Provider[] = [
  {
    id: "prov-1",
    name: "John Smith",
    businessName: "Smith's Plumbing Pro",
    rating: 4.9,
    reviewCount: 127,
    services: ["Pipe Repair", "Drain Cleaning", "Water Heater", "Fixture Installation"],
    categoryIds: ["cat-1"],
    hourlyRate: 85,
    verified: true,
    description: "Licensed master plumber with 15 years of experience. We handle everything from leaky faucets to full bathroom remodels.",
    yearsExperience: 15,
    completedJobs: 342,
    responseTime: "Usually responds in 1 hour",
    distance: 2.3,
    gallery: [],
  },
  {
    id: "prov-2",
    name: "Maria Garcia",
    businessName: "Sparkle Clean Co",
    rating: 4.8,
    reviewCount: 89,
    services: ["Deep Cleaning", "Regular Maintenance", "Move-In/Out", "Office Cleaning"],
    categoryIds: ["cat-4"],
    hourlyRate: 45,
    verified: true,
    description: "Professional cleaning team dedicated to making your home spotless. Eco-friendly products available.",
    yearsExperience: 8,
    completedJobs: 567,
    responseTime: "Usually responds in 30 min",
    distance: 1.8,
    gallery: [],
  },
  {
    id: "prov-3",
    name: "Mike Johnson",
    businessName: "Johnson Electric",
    rating: 4.7,
    reviewCount: 156,
    services: ["Wiring", "Panel Upgrades", "Lighting", "EV Charger Installation"],
    categoryIds: ["cat-2"],
    hourlyRate: 95,
    verified: true,
    description: "Certified electrician specializing in residential and light commercial work. Safety is our priority.",
    yearsExperience: 12,
    completedJobs: 423,
    responseTime: "Usually responds in 2 hours",
    distance: 3.1,
    gallery: [],
  },
  {
    id: "prov-4",
    name: "Sarah Chen",
    businessName: "CoolAir HVAC Services",
    rating: 4.9,
    reviewCount: 203,
    services: ["AC Repair", "Furnace Service", "Duct Cleaning", "System Installation"],
    categoryIds: ["cat-3"],
    hourlyRate: 90,
    verified: true,
    description: "Family-owned HVAC company serving the Bay Area for 20 years. 24/7 emergency service available.",
    yearsExperience: 20,
    completedJobs: 892,
    responseTime: "Usually responds in 1 hour",
    distance: 4.2,
    gallery: [],
  },
  {
    id: "prov-5",
    name: "David Williams",
    businessName: "Green Thumb Landscaping",
    rating: 4.6,
    reviewCount: 78,
    services: ["Lawn Care", "Garden Design", "Tree Trimming", "Irrigation"],
    categoryIds: ["cat-5"],
    hourlyRate: 55,
    verified: true,
    description: "Transform your outdoor space with our expert landscaping services. Free consultations available.",
    yearsExperience: 10,
    completedJobs: 234,
    responseTime: "Usually responds in 3 hours",
    distance: 5.0,
    gallery: [],
  },
  {
    id: "prov-6",
    name: "Lisa Brown",
    businessName: "Perfect Paint Pros",
    rating: 4.8,
    reviewCount: 112,
    services: ["Interior Painting", "Exterior Painting", "Cabinet Refinishing", "Wallpaper"],
    categoryIds: ["cat-6"],
    hourlyRate: 65,
    verified: true,
    description: "Professional painters delivering flawless finishes. We prep, paint, and clean up.",
    yearsExperience: 14,
    completedJobs: 456,
    responseTime: "Usually responds in 2 hours",
    distance: 2.7,
    gallery: [],
  },
  {
    id: "prov-7",
    name: "Tom Anderson",
    businessName: "TopShield Roofing",
    rating: 4.7,
    reviewCount: 67,
    services: ["Roof Repair", "Full Replacement", "Inspection", "Gutter Installation"],
    categoryIds: ["cat-7"],
    hourlyRate: 75,
    verified: true,
    description: "Licensed roofing contractor with expertise in all roof types. Storm damage specialists.",
    yearsExperience: 18,
    completedJobs: 289,
    responseTime: "Usually responds in 4 hours",
    distance: 6.1,
    gallery: [],
  },
  {
    id: "prov-8",
    name: "Robert Martinez",
    businessName: "Handy Bob's Services",
    rating: 4.5,
    reviewCount: 94,
    services: ["General Repairs", "Furniture Assembly", "Mounting", "Door Installation"],
    categoryIds: ["cat-8"],
    hourlyRate: 50,
    verified: true,
    description: "No job too small! Your one-stop shop for all home repairs and installations.",
    yearsExperience: 7,
    completedJobs: 678,
    responseTime: "Usually responds in 1 hour",
    distance: 1.5,
    gallery: [],
  },
  {
    id: "prov-9",
    name: "Kevin Park",
    businessName: "Park Plumbing & Heating",
    rating: 4.8,
    reviewCount: 145,
    services: ["Pipe Repair", "Boiler Service", "Gas Lines", "Bathroom Remodel"],
    categoryIds: ["cat-1"],
    hourlyRate: 80,
    verified: true,
    description: "Full-service plumbing and heating solutions. Licensed, bonded, and insured.",
    yearsExperience: 11,
    completedJobs: 398,
    responseTime: "Usually responds in 2 hours",
    distance: 3.4,
    gallery: [],
  },
  {
    id: "prov-10",
    name: "Amanda Lee",
    businessName: "Pristine Home Cleaning",
    rating: 4.9,
    reviewCount: 234,
    services: ["Deep Cleaning", "Weekly Service", "Post-Construction", "Carpet Cleaning"],
    categoryIds: ["cat-4"],
    hourlyRate: 50,
    verified: true,
    description: "Top-rated cleaning service with trained professionals. Satisfaction guaranteed.",
    yearsExperience: 6,
    completedJobs: 1023,
    responseTime: "Usually responds in 20 min",
    distance: 2.1,
    gallery: [],
  },
  {
    id: "prov-11",
    name: "Chris Taylor",
    businessName: "Taylor Electric Co",
    rating: 4.6,
    reviewCount: 88,
    services: ["Rewiring", "Outlet Installation", "Smart Home", "Generator Install"],
    categoryIds: ["cat-2"],
    hourlyRate: 90,
    verified: true,
    description: "Modern electrical solutions for modern homes. Smart home automation experts.",
    yearsExperience: 9,
    completedJobs: 312,
    responseTime: "Usually responds in 3 hours",
    distance: 4.8,
    gallery: [],
  },
  {
    id: "prov-12",
    name: "Jennifer Wong",
    businessName: "Comfort Zone HVAC",
    rating: 4.7,
    reviewCount: 167,
    services: ["AC Installation", "Heat Pump", "Maintenance Plans", "Air Quality"],
    categoryIds: ["cat-3"],
    hourlyRate: 85,
    verified: true,
    description: "Keep your home comfortable year-round. Energy-efficient solutions our specialty.",
    yearsExperience: 13,
    completedJobs: 534,
    responseTime: "Usually responds in 1 hour",
    distance: 3.9,
    gallery: [],
  },
];

const HOMEOWNER_ID = "homeowner-1";

export const DEFAULT_HOMEOWNER: HomeownerProfile = {
  id: HOMEOWNER_ID,
  name: "Alex Johnson",
  email: "alex@example.com",
  phone: "(415) 555-0123",
  addresses: [
    {
      id: "addr-1",
      label: "Home",
      street: "123 Main Street",
      city: "San Francisco",
      state: "CA",
      zip: "94102",
      isDefault: true,
    },
    {
      id: "addr-2",
      label: "Office",
      street: "456 Market Street",
      city: "San Francisco",
      state: "CA",
      zip: "94105",
      isDefault: false,
    },
  ],
  paymentMethods: [
    {
      id: "pm-1",
      type: "card",
      label: "Visa",
      last4: "4242",
      expiryMonth: 12,
      expiryYear: 2027,
      isDefault: true,
    },
    {
      id: "pm-2",
      type: "apple_pay",
      label: "Apple Pay",
      last4: "1234",
      isDefault: false,
    },
  ],
  createdAt: "2024-06-15T10:00:00Z",
};

function createTimelineEvents(job: Partial<Job>): Job["timeline"] {
  const events: Job["timeline"] = [
    {
      id: `tl-${job.id}-1`,
      type: "status_change",
      title: "Job Requested",
      description: "You submitted a service request",
      timestamp: job.createdAt || new Date().toISOString(),
    },
  ];

  if (job.status !== "requested") {
    events.push({
      id: `tl-${job.id}-2`,
      type: "status_change",
      title: "Job Scheduled",
      description: `Scheduled for ${job.scheduledDate} at ${job.scheduledTime}`,
      timestamp: new Date(new Date(job.createdAt || "").getTime() + 3600000).toISOString(),
    });
  }

  if (["in_progress", "awaiting_payment", "completed", "paid", "closed"].includes(job.status || "")) {
    events.push({
      id: `tl-${job.id}-3`,
      type: "status_change",
      title: "Work Started",
      description: "Provider arrived and began work",
      timestamp: new Date(new Date(job.scheduledDate || "").getTime()).toISOString(),
    });
  }

  if (["awaiting_payment", "completed", "paid", "closed"].includes(job.status || "")) {
    events.push({
      id: `tl-${job.id}-4`,
      type: "status_change",
      title: "Work Completed",
      description: "Provider finished the job",
      timestamp: new Date(new Date(job.scheduledDate || "").getTime() + 7200000).toISOString(),
    });
    events.push({
      id: `tl-${job.id}-5`,
      type: "note",
      title: "Invoice Sent",
      description: "Provider sent the final invoice",
      timestamp: new Date(new Date(job.scheduledDate || "").getTime() + 7800000).toISOString(),
    });
  }

  if (["paid", "closed"].includes(job.status || "")) {
    events.push({
      id: `tl-${job.id}-6`,
      type: "payment",
      title: "Payment Received",
      description: `Paid $${job.finalPrice || job.estimatedPrice}`,
      timestamp: new Date(new Date(job.scheduledDate || "").getTime() + 86400000).toISOString(),
    });
  }

  return events;
}

export const SEED_JOBS: Job[] = [
  {
    id: "job-1",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-1",
    providerName: "John Smith",
    providerBusinessName: "Smith's Plumbing Pro",
    categoryId: "cat-1",
    service: "Pipe Repair",
    status: "closed",
    description: "Leaky pipe under kitchen sink causing water damage",
    urgency: "urgent",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-12-15",
    scheduledTime: "10:00 AM",
    estimatedPrice: 250,
    finalPrice: 275,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-1",
    receiptId: "rcpt-1",
    reviewId: "rev-1",
    createdAt: "2025-12-13T08:00:00Z",
    updatedAt: "2025-12-16T14:00:00Z",
  },
  {
    id: "job-2",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-2",
    providerName: "Maria Garcia",
    providerBusinessName: "Sparkle Clean Co",
    categoryId: "cat-4",
    service: "Deep Cleaning",
    status: "paid",
    description: "Full house deep cleaning before holiday guests arrive",
    urgency: "soon",
    size: "large",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-12-20",
    scheduledTime: "9:00 AM",
    estimatedPrice: 350,
    finalPrice: 350,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-2",
    receiptId: "rcpt-2",
    createdAt: "2025-12-18T10:00:00Z",
    updatedAt: "2025-12-21T12:00:00Z",
  },
  {
    id: "job-3",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-3",
    providerName: "Mike Johnson",
    providerBusinessName: "Johnson Electric",
    categoryId: "cat-2",
    service: "Panel Upgrade",
    status: "completed",
    description: "Upgrade electrical panel from 100A to 200A for EV charger",
    urgency: "flexible",
    size: "large",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-11-10",
    scheduledTime: "8:00 AM",
    estimatedPrice: 2500,
    finalPrice: 2800,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-3",
    createdAt: "2025-11-01T09:00:00Z",
    updatedAt: "2025-11-12T16:00:00Z",
  },
  {
    id: "job-4",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-4",
    providerName: "Sarah Chen",
    providerBusinessName: "CoolAir HVAC Services",
    categoryId: "cat-3",
    service: "AC Repair",
    status: "closed",
    description: "AC not cooling properly, making strange noise",
    urgency: "urgent",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-08-15",
    scheduledTime: "2:00 PM",
    estimatedPrice: 400,
    finalPrice: 425,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-4",
    receiptId: "rcpt-4",
    reviewId: "rev-4",
    createdAt: "2025-08-14T11:00:00Z",
    updatedAt: "2025-08-17T10:00:00Z",
  },
  {
    id: "job-5",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-6",
    providerName: "Lisa Brown",
    providerBusinessName: "Perfect Paint Pros",
    categoryId: "cat-6",
    service: "Interior Painting",
    status: "closed",
    description: "Paint living room and dining room, neutral colors",
    urgency: "flexible",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-09-20",
    scheduledTime: "9:00 AM",
    estimatedPrice: 1200,
    finalPrice: 1150,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-5",
    receiptId: "rcpt-5",
    reviewId: "rev-5",
    createdAt: "2025-09-15T14:00:00Z",
    updatedAt: "2025-09-23T11:00:00Z",
  },
  {
    id: "job-6",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-8",
    providerName: "Robert Martinez",
    providerBusinessName: "Handy Bob's Services",
    categoryId: "cat-8",
    service: "Furniture Assembly",
    status: "closed",
    description: "Assemble new IKEA bedroom furniture set",
    urgency: "flexible",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-10-05",
    scheduledTime: "11:00 AM",
    estimatedPrice: 150,
    finalPrice: 150,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-6",
    receiptId: "rcpt-6",
    reviewId: "rev-6",
    createdAt: "2025-10-03T16:00:00Z",
    updatedAt: "2025-10-05T14:00:00Z",
  },
  {
    id: "job-7",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-5",
    providerName: "David Williams",
    providerBusinessName: "Green Thumb Landscaping",
    categoryId: "cat-5",
    service: "Lawn Care",
    status: "closed",
    description: "Monthly lawn maintenance - mowing, edging, cleanup",
    urgency: "flexible",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-10-15",
    scheduledTime: "8:00 AM",
    estimatedPrice: 120,
    finalPrice: 120,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-7",
    receiptId: "rcpt-7",
    createdAt: "2025-10-10T09:00:00Z",
    updatedAt: "2025-10-15T11:00:00Z",
  },
  {
    id: "job-8",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-9",
    providerName: "Kevin Park",
    providerBusinessName: "Park Plumbing & Heating",
    categoryId: "cat-1",
    service: "Water Heater Service",
    status: "closed",
    description: "Annual water heater maintenance and flush",
    urgency: "flexible",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-11-20",
    scheduledTime: "10:00 AM",
    estimatedPrice: 180,
    finalPrice: 180,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-8",
    receiptId: "rcpt-8",
    createdAt: "2025-11-18T13:00:00Z",
    updatedAt: "2025-11-20T12:00:00Z",
  },
  {
    id: "job-9",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-10",
    providerName: "Amanda Lee",
    providerBusinessName: "Pristine Home Cleaning",
    categoryId: "cat-4",
    service: "Weekly Service",
    status: "closed",
    description: "Regular weekly cleaning - full house",
    urgency: "flexible",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-12-01",
    scheduledTime: "10:00 AM",
    estimatedPrice: 180,
    finalPrice: 180,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-9",
    receiptId: "rcpt-9",
    createdAt: "2025-11-28T11:00:00Z",
    updatedAt: "2025-12-01T13:00:00Z",
  },
  {
    id: "job-10",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-7",
    providerName: "Tom Anderson",
    providerBusinessName: "TopShield Roofing",
    categoryId: "cat-7",
    service: "Roof Inspection",
    status: "closed",
    description: "Annual roof inspection before rainy season",
    urgency: "soon",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2025-10-25",
    scheduledTime: "9:00 AM",
    estimatedPrice: 200,
    finalPrice: 200,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-10",
    receiptId: "rcpt-10",
    reviewId: "rev-10",
    createdAt: "2025-10-20T10:00:00Z",
    updatedAt: "2025-10-25T11:00:00Z",
  },
  {
    id: "job-11",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-4",
    providerName: "Sarah Chen",
    providerBusinessName: "CoolAir HVAC Services",
    categoryId: "cat-3",
    service: "Furnace Maintenance",
    status: "in_progress",
    description: "Annual furnace tune-up and filter replacement",
    urgency: "soon",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2026-01-27",
    scheduledTime: "10:00 AM",
    estimatedPrice: 280,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    createdAt: "2026-01-20T09:00:00Z",
    updatedAt: "2026-01-27T10:30:00Z",
  },
  {
    id: "job-12",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-3",
    providerName: "Mike Johnson",
    providerBusinessName: "Johnson Electric",
    categoryId: "cat-2",
    service: "Outlet Installation",
    status: "awaiting_payment",
    description: "Install 3 new outlets in home office",
    urgency: "flexible",
    size: "small",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2026-01-25",
    scheduledTime: "2:00 PM",
    estimatedPrice: 350,
    finalPrice: 375,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    invoiceId: "inv-12",
    createdAt: "2026-01-22T14:00:00Z",
    updatedAt: "2026-01-25T16:00:00Z",
  },
  {
    id: "job-13",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-1",
    providerName: "John Smith",
    providerBusinessName: "Smith's Plumbing Pro",
    categoryId: "cat-1",
    service: "Drain Cleaning",
    status: "in_progress",
    description: "Main drain line is slow, needs professional cleaning",
    urgency: "urgent",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2026-01-27",
    scheduledTime: "1:00 PM",
    estimatedPrice: 225,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    createdAt: "2026-01-26T11:00:00Z",
    updatedAt: "2026-01-27T13:15:00Z",
  },
  {
    id: "job-14",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-2",
    providerName: "Maria Garcia",
    providerBusinessName: "Sparkle Clean Co",
    categoryId: "cat-4",
    service: "Deep Cleaning",
    status: "scheduled",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    description: "Monthly deep cleaning service",
    urgency: "flexible",
    size: "large",
    scheduledDate: "2026-02-01",
    scheduledTime: "9:00 AM",
    estimatedPrice: 320,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    createdAt: "2026-01-25T10:00:00Z",
    updatedAt: "2026-01-25T10:00:00Z",
  },
  {
    id: "job-15",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-5",
    providerName: "David Williams",
    providerBusinessName: "Green Thumb Landscaping",
    categoryId: "cat-5",
    service: "Tree Trimming",
    status: "scheduled",
    description: "Trim oak tree branches hanging over roof",
    urgency: "soon",
    size: "medium",
    addressId: "addr-1",
    address: "123 Main Street, San Francisco, CA 94102",
    scheduledDate: "2026-02-10",
    scheduledTime: "8:00 AM",
    estimatedPrice: 450,
    photosBefore: [],
    photosAfter: [],
    timeline: [],
    createdAt: "2026-01-24T15:00:00Z",
    updatedAt: "2026-01-24T15:00:00Z",
  },
].map(job => ({ ...job, timeline: createTimelineEvents(job as Partial<Job>) })) as Job[];

export const SEED_INVOICES: Invoice[] = [
  {
    id: "inv-1",
    jobId: "job-1",
    providerId: "prov-1",
    homeownerId: HOMEOWNER_ID,
    items: [{ description: "Replace corroded pipe section", quantity: 1, unitPrice: 150, total: 150 }],
    laborHours: 1.5,
    laborRate: 85,
    laborTotal: 127.50,
    materialsTotal: 150,
    subtotal: 277.50,
    tax: 0,
    total: 275,
    status: "paid",
    createdAt: "2025-12-15T14:00:00Z",
    paidAt: "2025-12-16T10:00:00Z",
  },
  {
    id: "inv-12",
    jobId: "job-12",
    providerId: "prov-3",
    homeownerId: HOMEOWNER_ID,
    items: [
      { description: "20A outlet installation", quantity: 3, unitPrice: 75, total: 225 },
      { description: "Electrical supplies", quantity: 1, unitPrice: 50, total: 50 },
    ],
    laborHours: 2,
    laborRate: 95,
    laborTotal: 190,
    materialsTotal: 185,
    subtotal: 375,
    tax: 0,
    total: 375,
    status: "sent",
    createdAt: "2026-01-25T16:00:00Z",
  },
];

export const SEED_RECEIPTS: Receipt[] = [
  {
    id: "rcpt-1",
    invoiceId: "inv-1",
    jobId: "job-1",
    amount: 275,
    paymentMethod: "Visa ending in 4242",
    transactionId: "txn_abc123",
    createdAt: "2025-12-16T10:00:00Z",
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: "rev-1",
    jobId: "job-1",
    providerId: "prov-1",
    homeownerId: HOMEOWNER_ID,
    homeownerName: "Alex Johnson",
    rating: 5,
    comment: "John was professional, on time, and fixed the leak quickly. Highly recommend!",
    createdAt: "2025-12-17T09:00:00Z",
  },
  {
    id: "rev-4",
    jobId: "job-4",
    providerId: "prov-4",
    homeownerId: HOMEOWNER_ID,
    homeownerName: "Alex Johnson",
    rating: 5,
    comment: "Sarah saved us during a heat wave! Fast response and fixed our AC same day.",
    createdAt: "2025-08-17T11:00:00Z",
  },
  {
    id: "rev-5",
    jobId: "job-5",
    providerId: "prov-6",
    homeownerId: HOMEOWNER_ID,
    homeownerName: "Alex Johnson",
    rating: 4,
    comment: "Beautiful work! The rooms look amazing. Minor cleanup needed after.",
    createdAt: "2025-09-24T10:00:00Z",
  },
  {
    id: "rev-6",
    jobId: "job-6",
    providerId: "prov-8",
    homeownerId: HOMEOWNER_ID,
    homeownerName: "Alex Johnson",
    rating: 5,
    comment: "Bob assembled everything perfectly and was super friendly. Great value!",
    createdAt: "2025-10-06T09:00:00Z",
  },
  {
    id: "rev-10",
    jobId: "job-10",
    providerId: "prov-7",
    homeownerId: HOMEOWNER_ID,
    homeownerName: "Alex Johnson",
    rating: 5,
    comment: "Thorough inspection with detailed report. Found minor issues before they became problems.",
    createdAt: "2025-10-26T10:00:00Z",
  },
];

export const SEED_MESSAGE_THREADS: MessageThread[] = [
  {
    id: "thread-1",
    jobId: "job-11",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-4",
    providerName: "Sarah Chen",
    service: "Furnace Maintenance",
    lastMessage: "I'm working on your furnace now. Should be done within the hour.",
    lastMessageTime: "10 min ago",
    unreadCount: 1,
    messages: [
      {
        id: "msg-1-1",
        threadId: "thread-1",
        senderId: HOMEOWNER_ID,
        senderName: "Alex Johnson",
        senderType: "homeowner",
        content: "Hi Sarah, just confirming our appointment for today at 10 AM?",
        attachments: [],
        timestamp: "2026-01-27T08:30:00Z",
        read: true,
      },
      {
        id: "msg-1-2",
        threadId: "thread-1",
        senderId: "prov-4",
        senderName: "Sarah Chen",
        senderType: "provider",
        content: "Good morning! Yes, I'll be there at 10. See you soon!",
        attachments: [],
        timestamp: "2026-01-27T08:45:00Z",
        read: true,
      },
      {
        id: "msg-1-3",
        threadId: "thread-1",
        senderId: "prov-4",
        senderName: "Sarah Chen",
        senderType: "provider",
        content: "I'm working on your furnace now. Should be done within the hour.",
        attachments: [],
        timestamp: "2026-01-27T10:20:00Z",
        read: false,
      },
    ],
  },
  {
    id: "thread-2",
    jobId: "job-12",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-3",
    providerName: "Mike Johnson",
    service: "Outlet Installation",
    lastMessage: "Invoice has been sent. Please pay at your convenience.",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
    messages: [
      {
        id: "msg-2-1",
        threadId: "thread-2",
        senderId: HOMEOWNER_ID,
        senderName: "Alex Johnson",
        senderType: "homeowner",
        content: "Hi Mike, where exactly should I mark for the outlet locations?",
        attachments: [],
        timestamp: "2026-01-24T10:00:00Z",
        read: true,
      },
      {
        id: "msg-2-2",
        threadId: "thread-2",
        senderId: "prov-3",
        senderName: "Mike Johnson",
        senderType: "provider",
        content: "Just put some tape where you want them. I'll check the wiring routes when I arrive.",
        attachments: [],
        timestamp: "2026-01-24T10:15:00Z",
        read: true,
      },
      {
        id: "msg-2-3",
        threadId: "thread-2",
        senderId: "prov-3",
        senderName: "Mike Johnson",
        senderType: "provider",
        content: "All done! The outlets are installed and tested. Invoice has been sent. Please pay at your convenience.",
        attachments: [],
        timestamp: "2026-01-25T16:30:00Z",
        read: true,
      },
    ],
  },
  {
    id: "thread-3",
    jobId: "job-13",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-1",
    providerName: "John Smith",
    service: "Drain Cleaning",
    lastMessage: "On my way! Should arrive in about 15 minutes.",
    lastMessageTime: "30 min ago",
    unreadCount: 1,
    messages: [
      {
        id: "msg-3-1",
        threadId: "thread-3",
        senderId: HOMEOWNER_ID,
        senderName: "Alex Johnson",
        senderType: "homeowner",
        content: "Hi John, the drain is getting worse. Can you come earlier if possible?",
        attachments: [],
        timestamp: "2026-01-27T12:00:00Z",
        read: true,
      },
      {
        id: "msg-3-2",
        threadId: "thread-3",
        senderId: "prov-1",
        senderName: "John Smith",
        senderType: "provider",
        content: "I understand. Let me finish up my current job and I'll head over. Should be there around 1 PM.",
        attachments: [],
        timestamp: "2026-01-27T12:15:00Z",
        read: true,
      },
      {
        id: "msg-3-3",
        threadId: "thread-3",
        senderId: "prov-1",
        senderName: "John Smith",
        senderType: "provider",
        content: "On my way! Should arrive in about 15 minutes.",
        attachments: [],
        timestamp: "2026-01-27T12:45:00Z",
        read: false,
      },
    ],
  },
  {
    id: "thread-4",
    jobId: "job-14",
    homeownerId: HOMEOWNER_ID,
    providerId: "prov-2",
    providerName: "Maria Garcia",
    service: "Deep Cleaning",
    lastMessage: "Confirmed for Feb 1st at 9 AM. See you then!",
    lastMessageTime: "2 days ago",
    unreadCount: 0,
    messages: [
      {
        id: "msg-4-1",
        threadId: "thread-4",
        senderId: "prov-2",
        senderName: "Maria Garcia",
        senderType: "provider",
        content: "Hi Alex! Thank you for booking with Sparkle Clean Co. We're looking forward to your cleaning session.",
        attachments: [],
        timestamp: "2026-01-25T10:30:00Z",
        read: true,
      },
      {
        id: "msg-4-2",
        threadId: "thread-4",
        senderId: HOMEOWNER_ID,
        senderName: "Alex Johnson",
        senderType: "homeowner",
        content: "Great! Please focus on the kitchen and bathrooms. Also, we have a cat.",
        attachments: [],
        timestamp: "2026-01-25T11:00:00Z",
        read: true,
      },
      {
        id: "msg-4-3",
        threadId: "thread-4",
        senderId: "prov-2",
        senderName: "Maria Garcia",
        senderType: "provider",
        content: "Noted! We'll make sure to use pet-friendly products. Confirmed for Feb 1st at 9 AM. See you then!",
        attachments: [],
        timestamp: "2026-01-25T11:15:00Z",
        read: true,
      },
    ],
  },
];

export const SEED_QUOTES: Quote[] = [
  {
    id: "quote-1",
    providerId: "prov-6",
    providerName: "Lisa Brown",
    homeownerId: HOMEOWNER_ID,
    service: "Cabinet Refinishing",
    description: "Refinish all kitchen cabinets - sand, prime, and paint white",
    estimatedHours: 24,
    laborRate: 65,
    materialsEstimate: 450,
    totalEstimate: 2010,
    validUntil: "2026-02-15",
    status: "pending",
    createdAt: "2026-01-26T14:00:00Z",
  },
];

export function generateTimeSlots(providerId: string, startDate: Date, days: number = 14): TimeSlot[] {
  const slots: TimeSlot[] = [];
  const startHour = 8;
  const endHour = 17;
  
  for (let d = 0; d < days; d++) {
    const date = new Date(startDate);
    date.setDate(date.getDate() + d);
    
    if (date.getDay() === 0) continue;
    
    for (let h = startHour; h < endHour; h += 2) {
      const isAvailable = Math.random() > 0.3;
      slots.push({
        id: `slot-${providerId}-${d}-${h}`,
        date: date.toISOString().split('T')[0],
        startTime: `${h}:00`,
        endTime: `${h + 2}:00`,
        available: isAvailable,
      });
    }
  }
  
  return slots;
}
